### ISSUE TITLE
[Proposta Servizio ] - cheshirecat

### ISSUE THREAD

**Issue by AndreaGelmini** [Zavy86/video-corso-vps#2]
Ciao 

è da un pò che te lo volevo segnalare. Sarebbe proprio carino se un video trattasse l'installazione (è semplice) di https://cheshirecat.ai/

**Comment by Zavy86** [comment]
sarebbe da provare.. gira solo su cpu o necessità di gpu che tu sappia?

**Comment by AndreaGelmini** [comment]
Si è molto interessante. Lo usa anche Giuppi per l'assistente allo studio nel suo sito. 

è un Framework scritto in python per la creazione di agenti AI, agnostico rispetto al modello in quanto usa modelli in cloud o in locale con Ollama. 
e' OS ed è tutto Italiano!!

dovrebbe bastare far girare 

```yml
services:

  cheshire-cat-core:
    image: ghcr.io/cheshire-cat-ai/core:latest
    container_name: cheshire_cat_core
    depends_on:
      - cheshire-cat-vector-memory
    env_file:
      - .env
    ports:
      - 1865:80
    volumes:
      - ./static:/app/cat/static
      - ./plugins:/app/cat/plugins
      - ./data:/app/cat/data
    restart: unless-stopped

  cheshire-cat-vector-memory:
    image: qdrant/qdrant:latest
    container_name: cheshire_cat_vector_memory
    expose:
      - 6333
    volumes:
      - ./long_term_memory/vector:/qdrant/storage
    restart: unless-stopped
```


PS. 
La versione che si base su ollama può essere installato con supporto GPU o solo CPU. Io ho provato quest'ultimo ma con pessimi risultati. 

se non lo ricordo male lo installai sul vecchio pc cosi 

```yml
services:

  cheshire-cat-core:
    image: ghcr.io/cheshire-cat-ai/core:latest
    container_name: cheshire_cat_core
    depends_on:
      - ollama
    ports:
      - 1865:80
    volumes:
      - ./static:/app/cat/static
      - ./plugins:/app/cat/plugins
      - ./data:/app/cat/data
    restart: unless-stopped

  ollama:
    container_name: ollama_cat
    image: ollama/ollama:latest
    volumes:
      - ./ollama:/root/.ollama
    expose:
      - 11434
```

Ma per ovvi motivi di budget non penso sia il caso e necessario installare ollama su OCIFT.
